### ISSUE TITLE
Invalid isoformat string for servers in UTC

### ISSUE THREAD

**Issue by ghost** [gerlos/bbbattendance#1]
Hi,

I'm running this with Python 3.8.5 from miniconda.

With an installation with timezone "UTC" I get:

```
(base) user@server:~$ ./bbbattendance.py 2021-03-10
User didn't provided any output file name, data will be saved to bbb-report-2021-03-10.csv
Traceback (most recent call last):
  File "./bbbattendance.py", line 253, in <module>
    parsed_attendance = parse_data(raw_attendance)
  File "./bbbattendance.py", line 156, in parse_data
    timestamp = dt.datetime.fromisoformat(line[0:29])
ValueError: Invalid isoformat string: '2021-03-10T08:36:25.379Z INFO'
```

Appearantly the parser doesn't expect a "Z" there and parses the "INFO" part that throws off the datetime lib...

changing the line 156

from

```
timestamp = dt.datetime.fromisoformat(line[0:29])
```

to 

```
timestamp = dt.datetime.fromisoformat(line[0:23])
```

cuts the string short of the "Z INFO" part and makes it work :)

Maybe there is a more flexible way to do this. Anyway, I'm leaving this work-around here, for
other people who might run into the same problem.

Thanks & Bye,
Chris

**Comment by gerlos** [comment]
Thanks! I'm reviewing your suggestion and I'll include it in the code after some test. 

Can you provide please some sample lines of your log file, so I can check if the changes solve the problem?

**Comment by gerlos** [comment]
I pushed a fix to main, feel free to test it and report back here
